KERNELDIR := /lib/modules/`uname -r`/build


all:
	$(MAKE) -C $(KERNELDIR) M=`pwd` modules

modules_install:
	$(MAKE) -C $(KERNELDIR) M=`pwd` modules_install

clean:
	$(MAKE) -C $(KERNELDIR) M=`pwd` clean


