.PHONY: clean All

All:
	@echo "----------Building project:[ threads - Debug ]----------"
	@cd "threads" && "$(MAKE)" -f  "threads.mk"
clean:
	@echo "----------Cleaning project:[ threads - Debug ]----------"
	@cd "threads" && "$(MAKE)" -f  "threads.mk" clean
